version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: colombia-ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped

  chroma:
    image: chromadb/chroma:latest
    container_name: colombia-chroma
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/chroma
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    restart: unless-stopped

  api:
    build: .
    container_name: colombia-rag-api
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - APP_ENV=production
      - OLLAMA_BASE_URL=http://ollama:11434
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
      - OLLAMA_MODEL_NAME=llama3.2:1b
      - LOG_LEVEL=INFO
    depends_on:
      - ollama
      - chroma
    restart: unless-stopped

volumes:
  ollama_data:
    driver: local
  chroma_data:
    driver: local

networks:
  default:
    name: colombia-rag-network